name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: go/src/github.com/Eun/watermark

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.x

      - name: Install GopherJS
        run: go get -u github.com/gopherjs/gopherjs

      - name: Build
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          export GOPATH=$(pwd)/go
          mkdir ./public
          cp go/src/github.com/Eun/watermark/cmd/web/index.html ./public/
          gopherjs build github.com/Eun/watermark/cmd/web -v -m --color -o ./public/web.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
